# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VideoGamesApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire', '~> 5.4.3'
  pod 'SDWebImage', '~> 5.0'
  pod 'ObjectMapper', '~> 4.2.0'
  # Pods for VideoGamesApp

end
